// File generated from our OpenAPI spec by Stainless.

package com.m3ter.sdk.models

import com.m3ter.sdk.core.JsonValue
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class LineItemTest {

    @Test
    fun createLineItem() {
        val lineItem =
            LineItem.builder()
                .id("id")
                .version(0L)
                .aggregationId("aggregationId")
                .averageUnitPrice(0.0)
                .balanceId("balanceId")
                .addBandUsage(
                    LineItem.BandUsage.builder()
                        .bandQuantity(0.0)
                        .bandSubtotal(0.0)
                        .bandUnits(0.0)
                        .creditTypeId("creditTypeId")
                        .fixedPrice(0.0)
                        .lowerLimit(0.0)
                        .pricingBandId("pricingBandId")
                        .unitPrice(0.0)
                        .unitSubtotal(0.0)
                        .build()
                )
                .billId("billId")
                .commitmentId("commitmentId")
                .compoundAggregationId("compoundAggregationId")
                .contractId("contractId")
                .conversionRate(0.0)
                .convertedSubtotal(0.0)
                .counterId("counterId")
                .createdBy("createdBy")
                .creditTypeId("creditTypeId")
                .currency("currency")
                .description("description")
                .dtCreated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .dtLastModified(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .group(
                    LineItem.Group.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .jsonUsageGenerated(true)
                .lastModifiedBy("lastModifiedBy")
                .lineItemType(LineItem.LineItemType.STANDING_CHARGE)
                .meterId("meterId")
                .planGroupId("planGroupId")
                .planId("planId")
                .pricingId("pricingId")
                .productCode("productCode")
                .productId("productId")
                .productName("productName")
                .quantity(0.0)
                .reasonId("reasonId")
                .referencedBillId("referencedBillId")
                .referencedLineItemId("referencedLineItemId")
                .segment(
                    LineItem.Segment.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .sequenceNumber(0L)
                .servicePeriodEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .servicePeriodStartDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .subtotal(0.0)
                .unit("unit")
                .units(0.0)
                .build()
        assertThat(lineItem).isNotNull
        assertThat(lineItem.id()).isEqualTo("id")
        assertThat(lineItem.version()).isEqualTo(0L)
        assertThat(lineItem.aggregationId()).contains("aggregationId")
        assertThat(lineItem.averageUnitPrice()).contains(0.0)
        assertThat(lineItem.balanceId()).contains("balanceId")
        assertThat(lineItem.bandUsage().get())
            .containsExactly(
                LineItem.BandUsage.builder()
                    .bandQuantity(0.0)
                    .bandSubtotal(0.0)
                    .bandUnits(0.0)
                    .creditTypeId("creditTypeId")
                    .fixedPrice(0.0)
                    .lowerLimit(0.0)
                    .pricingBandId("pricingBandId")
                    .unitPrice(0.0)
                    .unitSubtotal(0.0)
                    .build()
            )
        assertThat(lineItem.billId()).contains("billId")
        assertThat(lineItem.commitmentId()).contains("commitmentId")
        assertThat(lineItem.compoundAggregationId()).contains("compoundAggregationId")
        assertThat(lineItem.contractId()).contains("contractId")
        assertThat(lineItem.conversionRate()).contains(0.0)
        assertThat(lineItem.convertedSubtotal()).contains(0.0)
        assertThat(lineItem.counterId()).contains("counterId")
        assertThat(lineItem.createdBy()).contains("createdBy")
        assertThat(lineItem.creditTypeId()).contains("creditTypeId")
        assertThat(lineItem.currency()).contains("currency")
        assertThat(lineItem.description()).contains("description")
        assertThat(lineItem.dtCreated()).contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(lineItem.dtLastModified())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(lineItem.group())
            .contains(
                LineItem.Group.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(lineItem.jsonUsageGenerated()).contains(true)
        assertThat(lineItem.lastModifiedBy()).contains("lastModifiedBy")
        assertThat(lineItem.lineItemType()).contains(LineItem.LineItemType.STANDING_CHARGE)
        assertThat(lineItem.meterId()).contains("meterId")
        assertThat(lineItem.planGroupId()).contains("planGroupId")
        assertThat(lineItem.planId()).contains("planId")
        assertThat(lineItem.pricingId()).contains("pricingId")
        assertThat(lineItem.productCode()).contains("productCode")
        assertThat(lineItem.productId()).contains("productId")
        assertThat(lineItem.productName()).contains("productName")
        assertThat(lineItem.quantity()).contains(0.0)
        assertThat(lineItem.reasonId()).contains("reasonId")
        assertThat(lineItem.referencedBillId()).contains("referencedBillId")
        assertThat(lineItem.referencedLineItemId()).contains("referencedLineItemId")
        assertThat(lineItem.segment())
            .contains(
                LineItem.Segment.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(lineItem.sequenceNumber()).contains(0L)
        assertThat(lineItem.servicePeriodEndDate())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(lineItem.servicePeriodStartDate())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(lineItem.subtotal()).contains(0.0)
        assertThat(lineItem.unit()).contains("unit")
        assertThat(lineItem.units()).contains(0.0)
    }
}
